# Generated by Django 5.0.6 on 2024-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='updt_time',
            field=models.CharField(default='', max_length=15),
        ),
    ]
