# Generated by Django 5.0.6 on 2024-06-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_content_updt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
